### ISSUE TITLE
Wrong number of arguments for function call

### ISSUE THREAD

**Issue by rainerkohlberger** [jcjohnson/fast-neural-style#1]
Hi,
I get the error below when trying running train.lua like this:

`th train.lua -h5_file /media/rainer/dada/coco/coco10k.h5 -loss_network models/vgg16.t7 -style_image ~/neural-style/style/10/s08.png -style_image_size 256 -content_weights 1.0 -style_weights 5.0 -checkpoint_name checkpoint -gpu 0`

what's wrong? thanks!

/home/rainer/torch/install/bin/luajit: /home/rainer/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 6 module of nn.Sequential:
/home/rainer/torch/install/share/lua/5.1/nn/THNN.lua:109: wrong number of arguments for function call
stack traceback:
        [C]: in function 'v'
        /home/rainer/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialMaxPooling_updateOutput'
        ...ner/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:42: in function <...ner/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:31>
        [C]: in function 'xpcall'
        /home/rainer/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/rainer/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ./fast_neural_style/PerceptualCriterion.lua:78: in function 'setStyleTarget'
        train.lua:127: in function 'main'
        train.lua:320: in main chunk
        [C]: in function 'dofile'
        ...iner/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d50

**Comment by jcjohnson** [comment]
That is a weird error - can you try reinstalling torch, cutorch, nn, and
cunn?

**Comment by rainerkohlberger** [comment]
thanks!! seamed to do the trick, training now…
