### ISSUE TITLE
Script errors out when running pre-trained models

### ISSUE THREAD

**Issue by reddragon** [jcjohnson/fast-neural-style#10]
There seems to be a problem when downloading and running the pre-trained models as mentioned in the wiki. 

```
~/work/fast-neural-style on  master ⌚ 17:38:27
$ th fast_neural_style.lua -model models/eccv16/starry_night.t7 -input_image images/content/chicago.jpg -output_image out.png
ERROR: Could not load model from models/eccv16/starry_night.t7
You may need to download the pretrained models by running
bash models/instance_norm/download_models.sh

~/work/fast-neural-style on  master ⌚ 17:38:54
$ ls models/instance_norm/download_models.sh                                                                   ‹ruby-1.8.7-p374›
ls: models/instance_norm/download_models.sh: No such file or directory

~/work/fast-neural-style on  master ⌚ 17:39:00
$ ls models/eccv16/starry_night.t7                                                                             ‹ruby-1.8.7-p374›
models/eccv16/starry_night.t7
```

1. `models/instance_norm/download_models.sh` does not exist.
2. `models/eccv16/starry_night.t7` exists, but script errors out, not clear why.

**Comment by reddragon** [comment]
Debugging this on `th` provided some hints. Adding `require 'nn.SpatialReflectionPadding'` to the top of the script, allows the script to move ahead of the original error, but fails somewhere else. Please let me know if this is something new. I am still new to Torch.

```
$ th fast_neural_style.lua -model models/eccv16/starry_night.t7 -input_image images/content/chicago.jpg -output_image out.png
/Users/gauravmenghani/torch-cl/install/bin/luajit: ...ch/install/share/lua/5.1/nn/SpatialReflectionPadding.lua:14: attempt to call field 'SpatialReflectionPadding_updateOutput' (a nil value)
stack traceback:
	...ch/install/share/lua/5.1/nn/SpatialReflectionPadding.lua:14: in function 'updateOutput'
	...enghani/torch-cl/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	fast_neural_style.lua:83: in function 'run_image'
	fast_neural_style.lua:120: in function 'main'
	fast_neural_style.lua:125: in main chunk
	[C]: in function 'dofile'
	...i/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0105cc1ba0
```

**Comment by jcjohnson** [comment]
Oops, I made a mistake with the error message here - as mentioned in the README, to download the pretrained models you should use the script

```bash
bash models/download_style_transfer_models.sh
```

For your second error, try updating the core torch packages:

```bash
luarocks install torch
luarocks install nn
```

**Comment by reddragon** [comment]
Thanks Justin. I did try updating the packages, unless I add the `require 'nn.SpatialReflectionPadding'` at the top of `fast_neural_style.lua`, the script refuses to load the model. This is happening on OSX, if it rings any bell.

**Comment by jcjohnson** [comment]
That is very weird - I'm not sure what's going on.

What happens when you run this script:

https://gist.github.com/jcjohnson/dea431055e71013f6dc259dbc90ce3ff

**Comment by reddragon** [comment]
Seems to be failing with this error on my MacBook Pro:
```
$ th test_reflection_padding.lua                                                                               ‹ruby-1.8.7-p374›
nil
/Users/gauravmenghani/torch-cl/install/bin/luajit: test_reflection_padding.lua:5: attempt to call field 'SpatialReflectionPadding' (a nil value)
stack traceback:
	test_reflection_padding.lua:5: in main chunk
	[C]: in function 'dofile'
	...i/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010b2e6ba0
```

However, on my Linux devserver, the script works fine
```
11655 ◯  th test_reflection_padding.lua
table: 0x4082f770
nn.SpatialReflectionPadding(l=2, r=2, t=2, b=2)
 2
 3
 8
 9
[torch.LongStorage of size 4]
```

Guessing this has something to do with the setup of torch/nn packages on my MacBook Pro.

**Comment by jcjohnson** [comment]
Yeah, I think something is wrong with your nn install on the MacBook. I have never used Torch on OSX so I'm not sure what the problem could be.

**Comment by reddragon** [comment]
Cool thanks. Seems like this issue should be closed. Sorry about the false alarm.

**Comment by eole1712** [comment]
hello @reddragon 
i'm in the same case then you, with test_reflection_padding.lua witch works fine on linux but not on my OSX
have you find a solution ?

**Comment by damirkotoric** [comment]
Same issue here but on Ubuntu.

**Comment by lihao2333** [comment]
Same issue here but on Ubuntu16.04 ...

**Comment by vvzen** [comment]
Same here on macOS..
When running the `https://gist.github.com/jcjohnson/dea431055e71013f6dc259dbc90ce3ff` script, this is the output:
```
nil
/Users/vvzen/torch-cl/install/bin/luajit: test_reflection_padding.lua:5: attempt to call field 'SpatialReflectionPadding' (a nil value)
stack traceback:
	test_reflection_padding.lua:5: in main chunk
	[C]: in function 'dofile'
	...n/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0107b47a00
```
