### ISSUE TITLE
Super Resolution never decrease after 160k iterations.

### ISSUE THREAD

**Issue by xiesiyuan** [jcjohnson/fast-neural-style#105]
Here comes my data prepare command:
`python make_sr_dataset.py --train_dir ../COCO/train2014 --val_dir ../COCO/val2014 --output_h5 file.h5 --sizes '8' --max_train 10000 --max_val 2000 --patch_size 288 --patch_stride 150`

Here comes my train command
`th train.lua -arch 'c9s1-64,R64,R64,R64,R64,u64,u64,u64,c9s1-3' -task upsample -h5_file file.h5 -tanh_constant 150 -preprocessing vgg -content_weights 1.0 -style_weights 0.0 -content_layers 9 -style_layers ' '  -upsample_factor '8' -num_iterations 200000 -gpu 0 -padding_type zero -batch_size 4 -use_instance_norm 0`

However,  the loss is change dramatically and never decrease after 160k iterations. 

Is there anyway to improve the net ?

**Comment by xiesiyuan** [comment]
@jcjohnson

**Comment by xiesiyuan** [comment]
I have fix it. There are two bugs in code cause this under upsamle mode. After fixing the source code, I achieve very good result after 10 hours training.

**Comment by flatflax** [comment]
hi,may i have the source code that after debug?

**Comment by AndreJFBico** [comment]
Would be nice to have the changed code, because im facing the same issue.

**Comment by groot-1313** [comment]
@xiesiyuan What changes did you make to the source code? Could you please share it!

**Comment by ceciliavision** [comment]
I'm trying to train a x4 super-resolution model. Originally I always got error of "CUDNN_STATUS_BAD_PARAM"

Then setting padding type to 'zero' solves my problem
