### ISSUE TITLE
Style image as input to fast_neural_style.lua?

### ISSUE THREAD

**Issue by curiousily** [jcjohnson/fast-neural-style#12]
Hi,

Is it possible to pass style image as input to one of your pre-trained fast-neural-style models?

It seems to me that it is possible to pass style image to slow_neural_style?

Thank you for your amazing work and making it open!

**Comment by jcjohnson** [comment]
The style image is baked into the trained model, so you cannot change the style image or any of the other parameters (style weight, content weight, etc) after training.

**Comment by curiousily** [comment]
Thanks!
