### ISSUE TITLE
Issue with image/init.lua 235

### ISSUE THREAD

**Issue by UTTAM2311** [jcjohnson/fast-neural-style#128]
/ th  slow_neural_style.lua -content_image 5632892-artistic-images.jpg -style_image artistic-images.jpg  -output_image out
throws the following error 

> home/lab/torch/install/bin/luajit: /home/lab/torch/install/share/lua/5.1/image/init.lua:235: Not a JPEG file: starts with 0x3c 0x21
stack traceback:
	[C]: in function 'load'
	/home/lab/torch/install/share/lua/5.1/image/init.lua:235: in function 'loader'
	/home/lab/torch/install/share/lua/5.1/image/init.lua:388: in function 'load'
	slow_neural_style.lua:101: in function 'main'
	slow_neural_style.lua:180: in main chunk
	[C]: in function 'dofile'
	.../lab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

Can someone help me with this issue ..

**Comment by lewisdonovan** [comment]
I'm having a similar issue, did you find a solution?
