### ISSUE TITLE
Support for OpenCL?

### ISSUE THREAD

**Issue by cathalgarvey** [jcjohnson/fast-neural-style#13]
I wish I could answer my own question, but I don't have a GPU yet. :/

Torch supports OpenCL pretty well now, compared to the huge lag in other popular frameworks. Is there a reason you suggest only CUDA in the readme, or should this work on any GPU-accelerated Torch setup?

Thanks!

**Comment by cathalgarvey** [comment]
[This function in utils](https://github.com/jcjohnson/fast-neural-style/blob/master/fast_neural_style/utils.lua#L55) suggests this repo does support OpenCL?

**Comment by jcjohnson** [comment]
Everything should already work with OpenCL if you add the flag `-backend opencl`.

**Comment by cathalgarvey** [comment]
Great, thanks!
Closes #13

--
@onetruecathal / @cathal@quitter.is
