### ISSUE TITLE
Request: Can someone generate some models for me?

### ISSUE THREAD

**Issue by ollietb** [jcjohnson/fast-neural-style#131]
I have a need for some models to be trained, specifically some Picasso paintings. I've tried generating them myself but it would take days on my PC and I can't spare the resource. Is there someone with a fast graphics card who can be hired to produce the models? Of course I will pay for their time. Please contact me on ollie.harridge@eventstag.com

**Comment by GregOriol** [comment]
Have a look at Amazon's EC2 p2/g3 or Google Cloud Platform instances, they have powerful GPUs

**Comment by ollietb** [comment]
Yes I tried those but the default AWS linux doesn't have the drivers installed for the GPUs and when I tried to install them I got errors that I wasn't able to resolve.
