### ISSUE TITLE
Not an issue - Characterizing and Improving Stability in Neural Style Transfer

### ISSUE THREAD

**Issue by jbgrant01** [jcjohnson/fast-neural-style#132]
Are you or anyone else going to put up a Github repostitory for the newly published paper? The results look amazing.

**Comment by deeprun** [comment]
which paper?

**Comment by 3DTOPO** [comment]
> which paper?

Probably the paper that is the subject of this thread.

**Comment by jbgrant01** [comment]
That is correct. The paper "Characterizing and Improving Stability in Neural Style Transfer" dated  5 May 2017 by Agrim Gupta, Justin Johnson, Alexandre Alahi and Li Fei-Fei on arXiv.

**Comment by jcjohnson** [comment]
Yes, I am hoping that we will release code and models for this paper some time this summer, but I don't have a concrete timeframe.

**Comment by jbgrant01** [comment]
That is great news. I will look forward to trying it out.

**Comment by tobymu** [comment]
@jcjohnson  Hello, are you or anyone else going to release the codes of this paper recently?
