### ISSUE TITLE
The Scream - Not Working

### ISSUE THREAD

**Issue by eric-yates** [jcjohnson/fast-neural-style#157]
I'm using the pre-trained model for The Scream, and I'm getting an image that looks like this:

![acadia-scream](https://user-images.githubusercontent.com/32752674/38902063-18d8caa2-425c-11e8-8103-5a03cb94a231.jpg)

Here is the command I used:

`th fast_neural_style.lua \`
`  -model models/instance_normalization/the_scream.t7 \`
`  -input_image images/content/acadia.jpg \`
`  -output_image images/output/acadia-scream.jpg`

Is this an issue or am I doing something wrong?

**Comment by ArtlyStyles** [comment]
seems you are using the wave model...

**Comment by 3DTOPO** [comment]
Appears to be the same as issue https://github.com/jcjohnson/fast-neural-style/issues/153

**Comment by eric-yates** [comment]
@ArtlyStyles, good catch. I copied and pasted the wrong command. Updated now.

@3DTOPO, for your issue none of the models work, correct? For mine, the eccv16 models work as expected, although none of the instance_normalization models work.

**Comment by eric-yates** [comment]
@sangjunnn came up with a wonderful solution to this in issue [#137](https://github.com/jcjohnson/fast-neural-style/issues/137). Basically, cd to the torch folder and run:

`~/torch$ sudo bash update.sh`
