### ISSUE TITLE
Some good results in super-resolution with Microsoft .Net Framework.

### ISSUE THREAD

**Issue by GlebSBrykin** [jcjohnson/fast-neural-style#161]
I managed to implement Your network in the language PascalABC.NET (for Microsoft .NET Framework) and get awesome results on a regular laptop with Windows8! I would like to show a few pictures.
![shutterstock_148170677](https://user-images.githubusercontent.com/36363358/39855785-ff264efe-5435-11e8-8367-724d97033c69.jpg)
It is original image.
![stanford](https://user-images.githubusercontent.com/36363358/39855837-2b37e926-5436-11e8-8939-a7ca6c3df5bf.jpg)
This image was generated with udnie style.
![stanford2](https://user-images.githubusercontent.com/36363358/39855893-5e7bc3a2-5436-11e8-9ed0-7da220a37764.jpg)
This image was generated with scream style and 90% style ratio(I added the ability to customize the styling depth.).
![stanford3](https://user-images.githubusercontent.com/36363358/39855943-a1426a7e-5436-11e8-92fb-0b0123b4a3ec.jpg)
This picture is stylized under waves.
![stanford4](https://user-images.githubusercontent.com/36363358/39856097-4b278c0e-5437-11e8-8f94-89863176740a.jpg)
This painting is stylized as la muse.
![stanford5](https://user-images.githubusercontent.com/36363358/39856143-77f4ce18-5437-11e8-8db7-b158417e52a3.jpg)
This painting is stylized as rain princess.
![stanford6](https://user-images.githubusercontent.com/36363358/39856183-99d4bf02-5437-11e8-82fb-7b94dbe0bd8d.jpg)
And this is the last style that was ported. Stylized as wreck.
The most interesting thing is that all calculations were made on the CPU and 3 gigabytes of RAM. Your network is quite productive!
I have a question: where can I find more styles to add to my app? I think they are already very much!

**Comment by suke27** [comment]
it seem result no related to Super resolution. it is style transfer

**Comment by GlebSBrykin** [comment]
Can you elaborate? The model is exactly what is used in the original project.
