### ISSUE TITLE
Is this the expected output?

### ISSUE THREAD

**Issue by NightMachinery** [jcjohnson/fast-neural-style#163]
Running 
```th fast_neural_style.lua \            
  -model models/instance_norm/feathers.t7 \
  -input_image images/content/chicago.jpg \
  -output_image out.png
``` 
gives me:
![image](https://user-images.githubusercontent.com/36224762/41206707-89c86ca4-6d1d-11e8-9365-473f926d2ba6.png)
```
th fast_neural_style.lua \             ✔  6518  02:15:02
  -model models/instance_norm/candy.t7 \
  -input_image images/content/chicago.jpg \
  -output_image out.png
```
:
![image](https://user-images.githubusercontent.com/36224762/41206718-af0f5a9a-6d1d-11e8-96ad-8a419a5f38ef.png)
What is going wrong?

**Comment by 3DTOPO** [comment]
See https://github.com/jcjohnson/fast-neural-style/issues/153

**Comment by NightMachinery** [comment]
https://github.com/jcjohnson/fast-neural-style/issues/137 solved my problem. (Updating torch.) And I had to remove Mono again for it to work.
