### ISSUE TITLE
ERROR: Could not load model from models/eccv16/starry_night.t7	

### ISSUE THREAD

**Issue by dekiesel** [jcjohnson/fast-neural-style#166]
I am trying to run

`th fast_neural_style.lua -model models/eccv16/starry_night.t7 -input_image images/content/source.jpg -output_image out.png
`

And I did download the models (at least I think so)

> me@ubuntu:~/fastdeepstyle/fast-neural-style$ bash models/download_style_transfer_models.sh 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   295  100   295    0     0    324      0 --:--:-- --:--:-- --:--:--   324
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   297  100   297    0     0    647      0 --:--:-- --:--:-- --:--:--   647
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   296  100   296    0     0    870      0 --:--:-- --:--:-- --:--:--   868
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   298  100   298    0     0    892      0 --:--:-- --:--:-- --:--:--   892
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   300  100   300    0     0    669      0 --:--:-- --:--:-- --:--:--   668
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   295  100   295    0     0    707      0 --:--:-- --:--:-- --:--:--   707
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   291  100   291    0     0    855      0 --:--:-- --:--:-- --:--:--   853
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   295  100   295    0     0    786      0 --:--:-- --:--:-- --:--:--   786
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   290  100   290    0     0    860      0 --:--:-- --:--:-- --:--:--   863
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   298  100   298    0     0    873      0 --:--:-- --:--:-- --:--:--   871

But the model I am trying to use is only 4K, is that correct?

`me@ubuntu:~/fastdeepstyle/fast-neural-style$ du -h models/eccv16/starry_night.t7
4.0K	models/eccv16/starry_night.t7
`

Could you let me know what I am doing wrong?

**Comment by llamasking** [comment]
The script does not download the whole file on my PC. I replaced my download script to use wget insead of curl. 

```
BASE_URL="http://cs.stanford.edu/people/jcjohns/fast-neural-style/models/"

mkdir -p models/instance_norm
cd models/instance_norm
wget -N --no-check-certificate "$BASE_URL/instance_norm/candy.t7"
wget -N --no-check-certificate "$BASE_URL/instance_norm/la_muse.t7"
wget -N --no-check-certificate "$BASE_URL/instance_norm/mosaic.t7"
wget -N --no-check-certificate "$BASE_URL/instance_norm/feathers.t7"
wget -N --no-check-certificate "$BASE_URL/instance_norm/the_scream.t7"
wget -N --no-check-certificate "$BASE_URL/instance_norm/udnie.t7"

mkdir -p ../eccv16
cd ../eccv16
wget -N --no-check-certificate "$BASE_URL/eccv16/the_wave.t7"
wget -N --no-check-certificate "$BASE_URL/eccv16/starry_night.t7"
wget -N --no-check-certificate "$BASE_URL/eccv16/la_muse.t7"
wget -N --no-check-certificate "$BASE_URL/eccv16/composition_vii.t7"
cd ../../
```

**Comment by dekiesel** [comment]
That works, thank you!

**Comment by yayashuxue** [comment]
Thanks! that really works!

**Comment by heziqiang** [comment]
thanks!
