### ISSUE TITLE
"opts" should be "opt"

### ISSUE THREAD

**Issue by junrushao1994** [jcjohnson/fast-neural-style#19]
Hi,

I think in https://github.com/jcjohnson/fast-neural-style/blob/master/train.lua#L187, https://github.com/jcjohnson/fast-neural-style/blob/master/train.lua#L189, https://github.com/jcjohnson/fast-neural-style/blob/master/slow_neural_style.lua#L161 and https://github.com/jcjohnson/fast-neural-style/blob/master/slow_neural_style.lua#L163, opts should be opt, since "opts" is not defined.

**Comment by jcjohnson** [comment]
Merged. Thanks!
