### ISSUE TITLE
training images & validation images ?

### ISSUE THREAD

**Issue by vic8760** [jcjohnson/fast-neural-style#21]
Sorry for this dumb question, but what exactly are the validation images ?, ive trained on the MS-COCO dataset, but never seen a validation folder on any neural training github software

Are they the content images ?

Also getting this error
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140659249059648:
  #000: ../../../src/H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: ../../../src/H5Dio.c line 437 in H5D__read(): src and dest data spaces have different sizes
    major: Invalid arguments to routine
    minor: Bad value
/usr/local/bin/luajit: /usr/local/share/lua/5.1/hdf5/dataset.lua:160: HDF5DataSet:partial() - failed reading data from [HDF5DataSet (83886080 /train2014/images DATASET)]
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/hdf5/dataset.lua:160: in function 'partial'
	./fast_neural_style/DataLoader.lua:79: in function 'getBatch'
	train.lua:160: in function 'opfunc'
	/usr/local/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	train.lua:240: in function 'main'
	train.lua:328: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004057a0

**Comment by ProGamerGov** [comment]
How did you download the COCO dataset?

I used the following commands: 

```
wget http://msvocds.blob.core.windows.net/coco2014/train2014.zip
wget http://msvocds.blob.core.windows.net/coco2014/val2014.zip
unzip train2014.zip
unzip val2014.zip
```

I had the val2014 and train2014 folders, which I then deleted after I made the file.h5 file with them. Both the validation and training data are stored in the h5 file and thus you do not need the train and val folders.

**Comment by vic8760** [comment]
Finally got it to work, i think i skipped the Python dependencies for virtual environments part, its crunching data now :monkey_face:

**Comment by SSeanHsu** [comment]
Is the file.h5 file used to stored the validation and training data? If we all use the COCO dataset, will we get the same HDF5 file? And why do I need the COCO dataset when I am going to train my own models? I am so confused. Can you help me? :)

**Comment by Mr-rxz** [comment]
How did you resolve it? I have the same problem. @vic8760
