### ISSUE TITLE
Error when running make_style_dataset 

### ISSUE THREAD

**Issue by toniaguirre** [jcjohnson/fast-neural-style#39]
I got this small error when trying to run the make_style_dataset script. I downloaded the COCO dataset and extracted it as I saw in another issue in the folder train. Did I write any of the flags wrong or smth?  
```
[antonioa1@wh-520-9-9 fnsm]$ python scripts/make_style_dataset.py --train_dir train/train2014/ --val_dir train/val2014/ --output_file train/output.h5 --max_images -1 --num_workers 2
  File "scripts/make_style_dataset.py", line 60
    print filename
                 ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by htoyryla** [comment]
Make sure to use python 2.7. Python 3 requires parentheses in print.

**Comment by toniaguirre** [comment]
that was it, thanks man!
