### ISSUE TITLE
Would it be possible to provide the h5 COCO data set file that was used for creating the style specific models? 

### ISSUE THREAD

**Issue by ProGamerGov** [jcjohnson/fast-neural-style#4]
On this page here https://github.com/jcjohnson/fast-neural-style/blob/master/doc/training.md
>All models in this repository were trained using the images from the COCO dataset.

**Comment by jcjohnson** [comment]
The H5 file is about 18 GB so I'm not sure of the best way to distribute it; it's probably easier to download the COCO dataset for yourself from here

http://mscoco.org/dataset/#download

and use the preprocessing script to rebuild it for yourself.

**Comment by tzatter** [comment]
Hello, thank you for awesome fast-neural-style
Can I use this torrent site to uploading data?
http://academictorrents.com/

**Comment by ProGamerGov** [comment]
@tzatter You could try this:

```
wget http://msvocds.blob.core.windows.net/coco2014/train2014.zip
wget http://msvocds.blob.core.windows.net/coco2014/val2014.zip
unzip train2014.zip
unzip val2014.zip
```

Not sure which ones @jcjohnson used though.

**Comment by jcjohnson** [comment]
@ProGamerGov Yep those are the files I used for training.

**Comment by tzatter** [comment]
Thank you for the correct download link
I uploaded the video of google street view to youtube
https://www.youtube.com/watch?v=BpH3n4oCzJk

**Comment by ZachisGit** [comment]
I found these, the second link hast a much faster download rate then the first one:
```
[  Speed ] [ Link ]
< 1 MB/sec http://msvocds.blob.core.windows.net/coco2014/train2014.zip
~ 7 MB/sec http://images.cocodataset.org/zips/train2014.zip
```
Hope this helps.
