### ISSUE TITLE
Any chance of OpenCL?

### ISSUE THREAD

**Issue by Mandibela** [jcjohnson/fast-neural-style#45]
Hi!

I have a RX480 with 8 gigs of ram. I have successfully installed Hugh Perkins' cltorch and used the regular neural-network and VGG19 with it. Looking at the fast-neural-style.lua I see it uses CUDA or nothing... Any chance of having a OpenCL backend as well?

**Comment by jcjohnson** [comment]
OpenCL support almost works, but there is a critical function that it not yet supported by cltorch:

https://github.com/hughperkins/distro-cl/issues/12

Once this gets fixed then fast-neural-style should work on OpenCL.

**Comment by Mandibela** [comment]
Ok. Thanks!
