### ISSUE TITLE
Missing neuralstyle2.utils

### ISSUE THREAD

**Issue by htoyryla** [jcjohnson/fast-neural-style#48]
Convert_network.lua has this require

```
local utils = require 'neuralstyle2.utils'
```

but this is not included in the project. Even tried to patch something together from the existing modules which were obvious but missing (such as InstanceNormalization) but still eventually failed.

**Comment by jcjohnson** [comment]
Whoops, should be fixed in https://github.com/jcjohnson/fast-neural-style/commit/63eb1b6952d91ce49a6d801bee7578347126617a.

**Comment by htoyryla** [comment]
Are you sure that fixes it? The first thing I had tried locally was to 

```
local utils = require 'fast_neural_style.utils'
```

When I then got errors about missing Torch classes, I further added

```
require 'fast_neural_style.ShaveImage'
require 'fast_neural_style.TotalVariation'
require 'fast_neural_style.InstanceNormalization'
```

After this, I got this, gave up at least for a moment and posted this issue:

```
/home/hannu/torch/install/bin/luajit: /home/hannu/torch/install/share/lua/5.1/cudnn/convert.lua:64: attempt to call method 'replace' (a nil value)
stack traceback:
	/home/hannu/torch/install/share/lua/5.1/cudnn/convert.lua:64: in function 'convert'
	scripts/convert_network.lua:46: in function 'main'
	scripts/convert_network.lua:57: in main chunk
	[C]: in function 'dofile'
	...annu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004065d0
```

**Comment by jcjohnson** [comment]
It works for me after simply changing the import.

What directory are you running the script from? Lua imports are relative to the current working directory, so for imports to work you need to run `convert_network.lua` from the root directory of the project and not from the `scripts` directory.

**Comment by htoyryla** [comment]
I am running it from the root directory, of course. Otherwise even the imports I have added (see above) would not work.

**Comment by jcjohnson** [comment]
Can you post the exact command you are trying to run? Maybe you are trying to use that script in a way I didn't anticipate.

**Comment by htoyryla** [comment]
```
th scripts/convert_network.lua -input_t7 fein009.t7 -output_t7 koe-cp.t7
```
What I'll do next is to make a clean clone and try with it.

**Comment by jcjohnson** [comment]
What is fein009.t7? Was it created with fast-neural-style or something else?

**Comment by htoyryla** [comment]
A model created by me in fast_neural_style. Trying the same with models/instance_norm/feathers.t7 fails exactly in the same way.

And without the imports for InstanceNormalization etc. it fails with an error asking for it.

Aah... is this not supposed to convert models created with fast-neural-style but import models to be used instead of VGG? Then I understand.

My use case is export the model created with fast-neural-style and used it in my second linux box which is without GPU at the moment.

**Comment by jcjohnson** [comment]
Yep, that's why it's crashing - the model conversion script expects that the only thing in the .t7 file is the model, but checkpoints from train.lua are tables containing the model under the "model" key. This is fixed in https://github.com/jcjohnson/fast-neural-style/commit/278094be4ed4e38b5f2ba8673f22325c822d4a11.

However you shouldn't need to use the model conversion script at all for checkpoints created with train.lua; it should always be saving CPU-compatible checkpoints. Do they crash when you try to use them on your secondary non-GPU box?

**Comment by htoyryla** [comment]
OK... of course, I should have remembered the checkpoints, seen it in the code, but doing multiple things in parallel is not good for thinking. 

I haven't tried running a model on the other box yet, so I'll assume that they will work. It was only  my experiences with other projects that GPU trained models would not work without conversion. Good, you have thought of that too. This can be closed.
