### ISSUE TITLE
Does it mean better result when using larger size set in preparing dataset

### ISSUE THREAD

**Issue by xpeng** [jcjohnson/fast-neural-style#51]
Hi, If i use --height 512 --width 512 when executing make_style_dataset.py to prepare dataset, does this mean the final result will be better after training stage? i saw the default is size 256. 

Thanks!

**Comment by jonmorton** [comment]
I have tried training with both 256x256 and 512x512 versions of the same dataset and didn't notice any substantial differences in the quality of the resulting models. But YMMV, of course.

**Comment by xpeng** [comment]
@jonmorton thanks, and i tested another size, it's true.
