### ISSUE TITLE
What kind of GPU

### ISSUE THREAD

**Issue by gecong** [jcjohnson/fast-neural-style#55]
Can you share what kind of GPU machine you are using and usually how long does it take to train a "instance-normalization" based model?

**Comment by jcjohnson** [comment]
The instance norm models were trained on a desktop with an Intel Core
i5-6500 CPU, 16GB RAM, and a Pascal Titan X GPU running Ubuntu 16.04 and
cuDNN 5.1. Training took somewhere in the ballpark of 4-6 hours per model
but I don't recall exactly.

**Comment by gecong** [comment]
Thank you for the information.
