### ISSUE TITLE
Commercial Use

### ISSUE THREAD

**Issue by 3DTOPO** [jcjohnson/fast-neural-style#64]
Hello @jcjohnson,

I sent you a private email a couple weeks back inquiring about commercial use of this project and I fear my message must have went to your junk mail folder.

Can you please email me so we can discuss the possibility? My email address is jeshua [at] 3dtopo [dot] com. 

Thanks!

**Comment by 3DTOPO** [comment]
Also @htoyryla would you email me? I am interested in collaboration with you.

**Comment by backnotprop** [comment]
bump

**Comment by backnotprop** [comment]
@jcjohnson @htoyryla 

Hi sorry to push this, but would really like to figure out a way to use this in a commercial environment. I have sent an email to Justin, but have not received a response.

**Comment by htoyryla** [comment]
@mdramos I have no say in this, you need to get in contact with Justin.
