### ISSUE TITLE
Could you please use Tensorflow, Theano, Keras, or Neon in the future?

### ISSUE THREAD

**Issue by shyamalschandra** [jcjohnson/fast-neural-style#7]
Somehow, Torch doesn't work on my machine (macOS 10.12 Sierra).

**Comment by jcjohnson** [comment]
I happen to like Torch, but I'd encourage others to reimplement using other frameworks! For example I've seen this one using Chainer:

https://github.com/yusuketomoto/chainer-fast-neuralstyle
