### ISSUE TITLE
No algorithms found that would fit in free GPU memory

### ISSUE THREAD

**Issue by zefengguo** [jcjohnson/fast-neural-style#91]
Hi,
     I don't know how to solve it,i need your help.
     
     when :
     th fast_neural_style.lua   -model models/instance_norm/candy.t7   -input_image     images/content/gzfori.jpg -output_image images/outputs/gzf01.jpg -gpu 0

--------
/home/torch/install/bin/luajit: /home/torch/install/share/lua/5.1/nn/Container.lua:67:
In 15 module of nn.Sequential:
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 1 module of nn.Sequential:
/home/torch/install/share/lua/5.1/cudnn/find.lua:503: No algorithms found that would fit in free GPU memory
stack traceback:
        [C]: in function 'error'
        /home/torch/install/share/lua/5.1/cudnn/find.lua:503: in function 'forwardAlgorithm'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:190: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:186>
        [C]: in function 'xpcall'
        /home/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function </home/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
        [C]: in function 'xpcall'
        /home/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        fast_neural_style.lua:82: in function 'run_image'
        fast_neural_style.lua:119: in function 'main'
        fast_neural_style.lua:124: in main chunk
        [C]: in function 'dofile'
        /home/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064f0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /home/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /home/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        fast_neural_style.lua:82: in function 'run_image'
        fast_neural_style.lua:119: in function 'main'
        fast_neural_style.lua:124: in main chunk
        [C]: in function 'dofile'
        /home/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064f0
-----------GPU:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 940M        Off  | 0000:04:00.0     Off |                  N/A |
| N/A   45C    P0    N/A /  N/A |      0MiB /   981MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Thanks

**Comment by jcjohnson** [comment]
Looks like you have a 940M GPU with only 1GB of memory - that is not enough GPU memory to run any of the pretrained models at the default image resolution. You can try reducing the resolution with the `-image_size` flag; the default value is 768, so you should try adding `-image_size 512` or other smaller resolutions.

**Comment by zefengguo** [comment]
Thank you, I try to change gtx1070, it works very well.
